//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobBankApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobDetail
    {
        public decimal Sl_No { get; set; }
        public string Organization { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Position { get; set; }
        public string JobID { get; set; }
        public System.DateTime SubmittedDate { get; set; }
        public string Location { get; set; }
        public string Status { get; set; }
        public string Other { get; set; }
    }
}
